name: Build Dumper-7

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest

    - name: Configure
      run: xmake f -p windows -a x64 -m release --yes

    - name: Build
      run: xmake build -v

    - name: Show where DLL is
      shell: cmd
      run: |
        echo === Поиск DLL ===
        dir /s /b *.dll 2>nul || echo DLL не найдены

    - name: Upload Dumper-7.dll
      uses: actions/upload-artifact@v4
      with:
        name: Dumper-7
        path: Bin/Release/Dumper-7.dll
